### ISSUE TITLE
open transaction , an error

### ISSUE THREAD

**Issue by reki-wf** [dgarcia360/NEMPay#23]
![dld9krauiaamd7k](https://user-images.githubusercontent.com/12903127/31387028-e4b8962c-ae03-11e7-9198-dae45809f42d.jpg)

this error popup.

**Comment by dgarcia360** [comment]
Hi reki-wf,

Thanks for reporting the error.

1) A patch has been included in the commit b2a81fee595a82f25d1c88808c81672f4cdd2f23 to avoid this error happening, but only tested in desktop browsers.

2) If using an android mobile phone, test it installing the APK.  Connect the device to your computer and type in the terminal:

ionic cordova build android --device

Hope it helps,

David
