### ISSUE TITLE
About display of secret key (at the time of new account creation and usual use)

### ISSUE THREAD

**Issue by mizunashi** [dgarcia360/NEMPay#24]
**Expected Behavior**
Originally it writes the secret key on paper.

**Current Behavior**
I can not copy it by selecting private key.
Many people are supposed to take screenshots.
Screenshots are accessible from many applications.
In order to avoid vulnerability, I want to put a warning to avoid screenshots.
In reality, there are few people who make notes on paper, so I think that it would be better to make it copyable to the clipboard.

**Steps to reproduce**
Screens for creating accounts and scenes for viewing secret keys in login state.

![screenshot_20171011-044013](https://user-images.githubusercontent.com/1645189/31407841-58e96a98-ae41-11e7-8b82-2f087c1a68ae.png)

![screenshot_20171011-044248](https://user-images.githubusercontent.com/1645189/31407999-f34f8edc-ae41-11e7-9264-55f8b7bb383f.png)

**Comment by dgarcia360** [comment]
Thanks @mizunashi!

In registration screen, two buttons have been added:

- Copy to clipboard
- I've copied it manually

In the account screen, added a "Copy" button.

David
