### ISSUE TITLE
Nothing happens when pressing the QR Load button.

### ISSUE THREAD

**Issue by mizunashi** [dgarcia360/NEMPay#25]
**Expected Behavior**
Pressing the QR reading button activates the QR code reader.

**Current Behavior**
Nothing happens even if you press the QR reading button.

(Only account import, QR works)

**Steps to reproduce**
Press the QR reading button in the upper right.

![screenshot_20171011-044723](https://user-images.githubusercontent.com/1645189/31408140-7fb71a84-ae42-11e7-99a8-9755a3a4107b.png)

**Comment by dgarcia360** [comment]
Thanks for reporting the bug!

It was not working in Android. To fix it, the icon was moved below the navigation bar.

David
