### ISSUE TITLE
In the address book, only the first letter is checked

### ISSUE THREAD

**Issue by mizunashi** [dgarcia360/NEMPay#26]
**Expected Behavior**
Register after confirming whether the address is official as NEM

**Current Behavior**
If the beginning is T or t, any short character string can be registered.

**Steps to reproduce**
Register the name and address in the address book.

![screenshot_20171011-051847](https://user-images.githubusercontent.com/1645189/31408741-8be5805a-ae44-11e7-825f-a91340cad41c.png)

**Comment by dgarcia360** [comment]
Thanks Rin for reporting the bug.

Fixed, checking also if the address has 40 characters.

David
