### ISSUE TITLE
Even if an existing account is imported with QR, it returns to the original screen without being registered

### ISSUE THREAD

**Issue by mizunashi** [dgarcia360/NEMPay#27]
**Expected Behavior**
When the QR code is read, a password input screen is displayed.
After entering the correct password, the account is added.

**Current Behavior**
After QR reading, "Necessity to enter password" is displayed.
However, there is no input screen and I will return to the registration screen.

(Just a pattern that JSON loaded with QR is copied to the clipboard)

**Steps to reproduce**
Register account → Capture QR

**Comment by dgarcia360** [comment]
Thanks!
Changed to expected behavior,
David
