### ISSUE TITLE
Confirmation about self node selection

### ISSUE THREAD

**Issue by mizunashi** [dgarcia360/NEMPay#28]
**Expected Behavior**
Node selection must be connected to a working super node.
And the delay of hight needs to be within the allowable range.

**Current Behavior**
Since it is a self-node selection, you can not select a node manually.

I will tell you about problems that are currently occurring in NanoWallet.
When san.nem.ninha is set with NanoWallet, Green Circle appears and appears to be functioning normally.
However, currently, san.nem.ninja does not have chains synchronized.
In response to such a problem, I'd like you to check whether automatic node selection works correctly.

**Steps to reproduce**
none

**Reference link:**
https://forum.nem.io/t/please-do-maintenance-or-stop-san-nem-ninja/8345

**Comment by dgarcia360** [comment]
I would prefer not to make the node manually selected. That would complicate the app for non blockchain expert users.

The node is picked by connection pool provided by nem library: https://nemlibrary.com/documentation/connection_pool/

 @guillemsole Is it possible to never pick san.nem.nija under any circunstantes? Is this node included in the nem-library actually?

Thanks,

David

**Comment by mizunashi** [comment]
Add note:  @guillemsole @aleixmorgadas

We have confirmed the phenomenon that "Online and Hight are delayed considerably".
It is predicted that the FileDiscripter on UNIX will run out of run-out and it will be impossible to record new chains.

At this time, if you select that server with NanoWallet, you will see a green display.
But transactions can not be handled well.

**Comment by aleixmorgadas** [comment]
I will remove `san.nem.ninja` from the connection pool default servers in nemlibrary.

I will pull request you when I fix it ☺️

**Comment by mizunashi** [comment]
sun.nem.ninja seems to be working normally now.
However, this phenomenon is being confirmed with various SNs.
There is a new workaround from BR, but it is still in the testing stage.

**Comment by aleixmorgadas** [comment]
can you share this work around please?

**Comment by mizunashi** [comment]
This is.
https://forum.nem.io/t/nem-supernode-rewards-program/1735/1730?u=mizunashi

**Comment by mizunashi** [comment]
Previously, I did not have the memory I saw, but when I look at the test results of the whole SN, the number of servers where Hight only has errors is increasing in some places.
https://supernodes.nem.io/history
