### ISSUE TITLE
On the transaction list screen, "Privete key has been copied" is displayed without any meaning.

### ISSUE THREAD

**Issue by mizunashi** [dgarcia360/NEMPay#29]
Expected Behavior
Even if you click on a place other than the menu on the screen on the transaction list screen, nothing happens.

Current Behavior
At the bottom of the screen, "Privete key has been copied" is displayed.
Repeat the display for the number of times you hit repeatedly when you hit repeatedly.

Steps to reproduce
On the transaction screen, click the part which seems to be unresponsive normally.

![screenshot_20171023-024247](https://user-images.githubusercontent.com/1645189/31864712-38138460-b79d-11e7-9a00-615263eebd0f.png)

**Comment by dgarcia360** [comment]
Hi Rin, 

Thanks for detecting it.

Strings ALERT_PRIVATE_KEY_COPIED and ALERT_ADDRESS_COPIED were switched. 

It should be fixed right now.

**Comment by mizunashi** [comment]
Thanks!
