### ISSUE TITLE
Account import can not be done with QR when newly registered.

### ISSUE THREAD

**Issue by mizunashi** [dgarcia360/NEMPay#30]
**Expected Behavior**
Select account import on the new registration screen.
QR leader is started with "loading of QR (display in English is unknown)".

**Current Behavior**
The QR reader does not start.

**Steps to reproduce**
Select account import on the new registration screen.
Press "Capture QR (Do not know the display in English)".

![screenshot_20171023-024436](https://user-images.githubusercontent.com/1645189/31864794-da902e4a-b79e-11e7-8c8a-8ecdbf727e26.png)

**Comment by dgarcia360** [comment]
Thanks @mizunashi for detecting the bug, fixed and updated!
