### ISSUE TITLE
Processing when there is no account on the account selection screen

### ISSUE THREAD

**Issue by mizunashi** [dgarcia360/NEMPay#31]
**Expected Behavior**
If you do not have an account and try to select an account, pop-ups with no choice are displayed.

**Current Behavior**
If the account does not exist, even if you select an account, it is nonresponsive and has no problem.

**Steps to reproduce**
Select an account without creating an account.
An account selection screen without choices is displayed.

**Comment by dgarcia360** [comment]
Great job spotting that issue! 

Just disabled account and password inputs if wallet length is equal to 0.
