### ISSUE TITLE
Even if you press send button via Address book, you can not proceed to the next screen.

### ISSUE THREAD

**Issue by mizunashi** [dgarcia360/NEMPay#33]
**Expected Behavior**
Select 1 person in Address book and press send button.
A transmission screen addressed to the selected address or a selection screen of the mosaic is displayed.

**Current Behavior**
Select 1 person in Address book and press send button.
At the center of the screen, "Please Wait" is forever displayed.

**Steps to reproduce**
Select 1 person in Address book and press send button.

![screenshot_20171023-184238](https://user-images.githubusercontent.com/1645189/31885354-35907a84-b82b-11e7-9d57-5bdbd3fde4cd.png)

**Comment by dgarcia360** [comment]
Hi Rin,
I'm not able to reproduce that error.

This is the behaviour I get while testing (tested with Android 7.1.2):

- Create a person in the Address book.
- Select that person
- Press send button.
- Then, "Please Wait" stop showing, while I'm redirected to balance screen to select the type of mosaic to be sent.

**Comment by mizunashi** [comment]
Version 1.0.1
I confirmed it now, it worked normally.
???
