### ISSUE TITLE
QR code does not support mosaic

### ISSUE THREAD

**Issue by daoka** [dgarcia360/NEMPay#42]
**Expected Behavior**
When the QR code is read, the mosaic set on the receive screen is reflected on the send screen.
(In the following captures, I expect "puthikun:thx" to be reflected as a mosaic of send screen.)

**Current Behavior**
Even if any mosaic is selected, it always becomes xem on the transmission screen.

**Step to reproduce**
1. select some mosaic and make a transition to the receive screen.
2. Launch the NEMPay app on another smart phone and read the QR code on receive screen.

**Other**
Like the QRCode contents it seems that the QR code does not correspond to the transmission of the mosaic.

QR code corresponding to transmission of mosaic is discussed in Japanese community.
In Japan, there is a growing demand for mobile wallets corresponding to mosaics.
 so I want you to specify the standard of the QR code corresponding to the mosaic.

## Receive screen capture
![screen_shot_2018-04-25_at_10_52_13](https://user-images.githubusercontent.com/90681/39224037-041f0606-4880-11e8-9fb2-08085d319e8e.png)

## Send screen capture
![screen_shot_2018-04-25_at_10_52_26](https://user-images.githubusercontent.com/90681/39224058-20ec9532-4880-11e8-9648-0050bb764e26.png)

## QRCode contents
<img width="526" alt="_2018-04-25_11_03_25" src="https://user-images.githubusercontent.com/90681/39224094-5e6a5ce6-4880-11e8-82d1-7a08eecdd17f.png">

**Comment by dgarcia360** [comment]
@daoka The current QRCode JSON "standard" doesn't allow attach mosaics. NEMPay uses Nem-library QR Service to generate invoices, which neither has the capability.
https://nemlibrary.com/documentation/service/#qrservice

NEMPay solves it partially:

1) First, select the mosaic from your balance you want to transfer.
2) Then scan the QRCode.

It is not the best solution, as it is not taking into account the type of mosaic scanned.

I will follow https://github.com/NemProject/NIP/pull/5 closely. Please, encourage @YuKimura45z and Japanese Community who are discussing the issue to upload the complete NIP.
