### ISSUE TITLE
Nempay sees transferable mosaics as non-transferable mosaics

### ISSUE THREAD

**Issue by baconbkk** [dgarcia360/NEMPay#44]
I am running on testnet and I have a bunch of mosaics that I have created that I guarantee are transferable. When I open up my wallet in nempay these mosaics are considered to be non- transferable and I can't send them. 

Not all transferable mosaics are seen to be non-transferable by Nempay though. 

**Nempay sees to be NON-transferable:**
- Mutable supply: False
- Transferable: True

**Nempay sees as TRANSFERABLE:**
- Mutable supply: True
- Transferable: True

**Steps to reproduce:**
- Login app
- Lands in 'Balance' page
- Choose a transferable mosaic (Transferable: True)
- Press send
- Alert pops up saying "Selected Mosaic is not transferable"

**Comment by dgarcia360** [comment]
Thanks for reporting the issue. After research, we have found it is related to nem-library current implementation.

As you detected, supplyMutabble and transferable properties are swapped.

I have already opened an issue, and currently preparing a pull-request.

https://github.com/aleixmorgadas/nem-library-ts/issues/32

**Comment by dgarcia360** [comment]
Pull request accepted https://github.com/aleixmorgadas/nem-library-ts/pull/33 and library version updated in NEMPay.
