### ISSUE TITLE
Retrieve wrong wallet when login

### ISSUE THREAD

**Issue by ChengChan** [dgarcia360/NEMPay#45]
Hi,

First, I login with 1st wallet and then quit the nempay app. Then I login again with 2nd wallet. The wallet name display at below is refer to 1st wallet.

<ion-title class="profile"><span [innerHTML]="walletName" style="padding-left: 10px"></span></ion-title>

Thanks.

**Comment by dgarcia360** [comment]
There is no reason to store which was the last wallet that logged in. Click on the wallet name, then select the previous wallet. 

However, there is one important thing to consider: there should be some way to remove a wallet from the phone.
