### ISSUE TITLE
Display transaction fees - nem fee and levy fee in confirmed transaction and unconfirmed transaction

### ISSUE THREAD

**Issue by ChengChan** [dgarcia360/NEMPay#46]
I could not display the transaction fees. Currently, the levy is undefined

_mosaics:Array(1)
0:Mosaic {mosaicId: MosaicId, quantity: 40000000}

_xem:XEM
amount:1
**levy:undefined**
mosaicId: MosaicId {namespaceId: "nem", name: "xem"}

**Comment by dgarcia360** [comment]
Thanks for reporting! It's probably a bug as should appear.

Do not hesitate to make a pull request yourself if you find the bug first. https://github.com/dgarcia360/NEMPay/blob/master/CONTRIBUTING.md

**Comment by ChengChan** [comment]
Any idea how to solve this problem? By when you will fix this?

**Comment by dgarcia360** [comment]
Updated the code to the latest nem-library release. It's working right now. There were some breaking changes between the version used and the most recent.

Some other code improvements will be coming soon.
