### ISSUE TITLE
Could not sign up with private key from nempay wallet itself

### ISSUE THREAD

**Issue by ChengChan** [dgarcia360/NEMPay#48]
Hi dgarcia,

I can sign up the wallet with private key if i scan the qrcode from the **nanowallet** account page after i enter my password. But I could not sign up the wallet with private key if i scan the qrcode from **another nempay account page** after i enter my password. It will throws an invalid password. This is failed as i know the nempay account qr code doesn't contain the private key. So what is the actual logic that need to implement at **Sign Up with private key page**

Thank you very much for previos fixed.

**Comment by dgarcia360** [comment]
You could use  **generateWalletQRText(password: Password, wallet: Wallet)** from NEM-Library QR service https://nemlibrary.com/documentation/service/#qrservice
