### ISSUE TITLE
Cannot import wallet with password shorter than 8 characters

### ISSUE THREAD

**Issue by calin-ciobanu** [dgarcia360/NEMPay#51]
Minimum number of characters in NEMPay is larger than in NanoWallet. I have a wallet with 6 digit password that I want to import. I scan the QR code, input the correct 6 digit password but I get an error message that the password is incorrect.

**Comment by dgarcia360** [comment]
[nem-library]( https://github.com/aleixmorgadas/nem-library-ts), the SDK NEMPay uses to interact with NEM blockchain and wallets, has this constraint:

https://github.com/aleixmorgadas/nem-library-ts/blob/master/src/models/wallet/Password.ts#L39

A workaround is to generate a new wallet from the private key using nanowallet, but setting a longer password.
