### ISSUE TITLE
Custom mosaics

### ISSUE THREAD

**Issue by Bitminereu** [dgarcia360/NEMPay#53]
How to add or change from xem to custom mosaics?

**Comment by Bitminereu** [comment]
Ok thanks, the current nempay using testnet? address start with T and is testnet, nem address start with N

**Comment by dgarcia360** [comment]
Your application can have two modes, NetworkTypes.TEST_NET and NetworkTypes.MAIN_NET. Depending on the environment that you want to use, you should call the bootstrap method, with MAIN_NET or TEST_NET.

- https://nemlibrary.com/documentation/overview/#installation
- https://github.com/dgarcia360/NEMPay/blob/master/src/providers/nem/nem.provider.ts#L33
